/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Blob/GetTemplateBackground/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    filename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Blob/GetTemplateBackgrounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Blob/GetDiploma/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    filename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Blob/GetDiplomaThumbnail/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    filename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Blob/PutDiploma": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DiplomaPutRequestDto"];
                    "text/json": components["schemas"]["DiplomaPutRequestDto"];
                    "application/*+json": components["schemas"]["DiplomaPutRequestDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StudentResponseDto"];
                        "application/json": components["schemas"]["StudentResponseDto"];
                        "text/json": components["schemas"]["StudentResponseDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Blob/GetFont/{fontName}/{fontType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fontName: string;
                    fontType: components["schemas"]["FontType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fontName: string;
                    fontType: components["schemas"]["FontType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        patch?: never;
        trace?: never;
    };
    "/api/Bootcamps/PostBootcamp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BootcampRequestDto"];
                    "text/json": components["schemas"]["BootcampRequestDto"];
                    "application/*+json": components["schemas"]["BootcampRequestDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BootcampResponseDto"];
                        "application/json": components["schemas"]["BootcampResponseDto"];
                        "text/json": components["schemas"]["BootcampResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Bootcamps/GetBootcamps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BootcampResponseDto"][];
                        "application/json": components["schemas"]["BootcampResponseDto"][];
                        "text/json": components["schemas"]["BootcampResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Bootcamps/GetBootcamp/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    guid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BootcampResponseDto"];
                        "application/json": components["schemas"]["BootcampResponseDto"];
                        "text/json": components["schemas"]["BootcampResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Bootcamps/DeleteBootcamp/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    guid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Bootcamps/PutBootcamp/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    guid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BootcampRequestUpdateDto"];
                    "text/json": components["schemas"]["BootcampRequestUpdateDto"];
                    "application/*+json": components["schemas"]["BootcampRequestUpdateDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BootcampResponseDto"];
                        "application/json": components["schemas"]["BootcampResponseDto"];
                        "text/json": components["schemas"]["BootcampResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Email/SendEmailToStudent/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    Title?: string;
                    Description?: string;
                };
                header?: never;
                path: {
                    guid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        File?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Snapshots/GetSnapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SnapshotResponseDto"][];
                        "application/json": components["schemas"]["SnapshotResponseDto"][];
                        "text/json": components["schemas"]["SnapshotResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Snapshots/GetSnapshot/{verificationCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    verificationCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SnapshotResponseDto"][];
                        "application/json": components["schemas"]["SnapshotResponseDto"][];
                        "text/json": components["schemas"]["SnapshotResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Snapshots/MakeSnapshotActive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MakeSnapshotActiveRequestDto"];
                    "text/json": components["schemas"]["MakeSnapshotActiveRequestDto"];
                    "application/*+json": components["schemas"]["MakeSnapshotActiveRequestDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SnapshotResponseDto"][];
                        "application/json": components["schemas"]["SnapshotResponseDto"][];
                        "text/json": components["schemas"]["SnapshotResponseDto"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Students/GetStudents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StudentResponseDto"][];
                        "application/json": components["schemas"]["StudentResponseDto"][];
                        "text/json": components["schemas"]["StudentResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Students/GetStudent/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    guid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StudentResponseDto"];
                        "application/json": components["schemas"]["StudentResponseDto"];
                        "text/json": components["schemas"]["StudentResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Students/GetStudentByVericationCode/{verificationCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    verificationCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StudentResponseDto"];
                        "application/json": components["schemas"]["StudentResponseDto"];
                        "text/json": components["schemas"]["StudentResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Students/UpdateStudent/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    guid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StudentUpdateRequestDto"];
                    "text/json": components["schemas"]["StudentUpdateRequestDto"];
                    "application/*+json": components["schemas"]["StudentUpdateRequestDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StudentResponseDto"];
                        "application/json": components["schemas"]["StudentResponseDto"];
                        "text/json": components["schemas"]["StudentResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Students/DeleteStudent/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    guid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Templates/GetTemplates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TemplateResponseDto"][];
                        "application/json": components["schemas"]["TemplateResponseDto"][];
                        "text/json": components["schemas"]["TemplateResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Templates/GetTemplate/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TemplateResponseDto"];
                        "application/json": components["schemas"]["TemplateResponseDto"];
                        "text/json": components["schemas"]["TemplateResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Templates/PostTemplate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TemplatePostRequestDto"];
                    "text/json": components["schemas"]["TemplatePostRequestDto"];
                    "application/*+json": components["schemas"]["TemplatePostRequestDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TemplateResponseDto"];
                        "application/json": components["schemas"]["TemplateResponseDto"];
                        "text/json": components["schemas"]["TemplateResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Templates/DeleteTemplate/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Templates/PutTemplate/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TemplateRequestDto"];
                    "text/json": components["schemas"]["TemplateRequestDto"];
                    "application/*+json": components["schemas"]["TemplateRequestDto"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TemplateResponseDto"];
                        "application/json": components["schemas"]["TemplateResponseDto"];
                        "text/json": components["schemas"]["TemplateResponseDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Tracks/GetTracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TracksResponseDto"][];
                        "application/json": components["schemas"]["TracksResponseDto"][];
                        "text/json": components["schemas"]["TracksResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/UserFonts/GetUserFonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserFontResponseDto"][];
                        "application/json": components["schemas"]["UserFontResponseDto"][];
                        "text/json": components["schemas"]["UserFontResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/UserFonts/PostUserFonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserFontRequestDto"][];
                    "text/json": components["schemas"]["UserFontRequestDto"][];
                    "application/*+json": components["schemas"]["UserFontRequestDto"][];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserFontResponseDto"][];
                        "application/json": components["schemas"]["UserFontResponseDto"][];
                        "text/json": components["schemas"]["UserFontResponseDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserFontResponseDto"][];
                        "application/json": components["schemas"]["UserFontResponseDto"][];
                        "text/json": components["schemas"]["UserFontResponseDto"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BootcampRequestDto: {
            /** Format: int32 */
            trackId?: number;
            /** Format: date-time */
            graduationDate?: string;
        };
        BootcampRequestUpdateDto: {
            students: components["schemas"]["StudentRequestDto"][];
            /** Format: int32 */
            templateId?: number;
            /** Format: int32 */
            trackId?: number;
            /** Format: date-time */
            graduationDate?: string;
        };
        BootcampResponseDto: {
            /** Format: uuid */
            guidId?: string;
            /** Format: date-time */
            graduationDate?: string;
            name?: string | null;
            track?: components["schemas"]["TracksResponseDto"];
            /** Format: int32 */
            templateId?: number;
            students?: components["schemas"]["StudentResponseDto"][] | null;
        };
        DiplomaPutRequestDto: {
            /** Format: uuid */
            studentGuidId?: string;
            imageData?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        FontType: 0 | 1 | 2;
        MakeSnapshotActiveRequestDto: {
            ids?: number[] | null;
            studentGuidIds?: string[] | null;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        SnapshotResponseDto: {
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            generatedAt?: string;
            bootcampName?: string | null;
            /** Format: uuid */
            bootcampGuidId?: string | null;
            /** Format: date-time */
            bootcampGraduationDate?: string;
            /** Format: uuid */
            studentGuidId?: string | null;
            studentName?: string | null;
            verificationCode?: string | null;
            templateName?: string | null;
            footer?: string | null;
            footerStyling?: components["schemas"]["TemplateStyle"];
            intro?: string | null;
            introStyling?: components["schemas"]["TemplateStyle"];
            main?: string | null;
            mainStyling?: components["schemas"]["TemplateStyle"];
            link?: string | null;
            linkStyling?: components["schemas"]["TemplateStyle"];
            basePdf?: string | null;
            /** Format: date-time */
            templateLastUpdated?: string;
            active?: boolean;
        };
        StudentRequestDto: {
            /** Format: uuid */
            guidId?: string | null;
            verificationCode: string;
            name: string;
            email?: string | null;
        };
        StudentResponseDto: {
            /** Format: uuid */
            guid?: string;
            verificationCode?: string | null;
            name?: string | null;
            email?: string | null;
            previewImageUrl?: string | null;
            previewImageLQIPUrl?: string | null;
            /** Format: date-time */
            lastGenerated?: string | null;
        };
        StudentUpdateRequestDto: {
            name?: string | null;
            /** Format: email */
            email?: string | null;
        };
        TemplateFieldStyleDto: {
            /** Format: int32 */
            id?: number;
            /** Format: double */
            xPos?: number | null;
            /** Format: double */
            yPos?: number | null;
            /** Format: double */
            width?: number | null;
            /** Format: double */
            height?: number | null;
            /** Format: double */
            fontSize?: number | null;
            fontColor?: string | null;
            fontName?: string | null;
            alignment?: string | null;
        };
        TemplatePostRequestDto: {
            /** Format: string */
            templateName: string;
        };
        TemplateRequestDto: {
            templateName?: string | null;
            footer?: string | null;
            footerStyling?: components["schemas"]["TemplateFieldStyleDto"];
            intro?: string | null;
            introStyling?: components["schemas"]["TemplateFieldStyleDto"];
            main?: string | null;
            mainStyling?: components["schemas"]["TemplateFieldStyleDto"];
            link?: string | null;
            linkStyling?: components["schemas"]["TemplateFieldStyleDto"];
            basePdf?: string | null;
            /** Format: date-time */
            pdfBackgroundLastUpdated?: string | null;
        };
        TemplateResponseDto: {
            /** Format: int32 */
            id?: number;
            templateName?: string | null;
            footer?: string | null;
            footerStyling?: components["schemas"]["TemplateFieldStyleDto"];
            intro?: string | null;
            introStyling?: components["schemas"]["TemplateFieldStyleDto"];
            main?: string | null;
            mainStyling?: components["schemas"]["TemplateFieldStyleDto"];
            link?: string | null;
            linkStyling?: components["schemas"]["TemplateFieldStyleDto"];
            basePdf?: string | null;
            /** Format: date-time */
            lastUpdated?: string;
            /** Format: date-time */
            pdfBackgroundLastUpdated?: string;
        };
        TemplateStyle: {
            /** Format: int32 */
            id?: number;
            /** Format: double */
            xPos?: number | null;
            /** Format: double */
            yPos?: number | null;
            /** Format: double */
            width?: number | null;
            /** Format: double */
            height?: number | null;
            /** Format: double */
            fontSize?: number | null;
            fontColor?: string | null;
            fontName?: string | null;
            alignment?: string | null;
        };
        TracksResponseDto: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            tag?: string | null;
            bootcamps?: components["schemas"]["BootcampResponseDto"][] | null;
        };
        UserFontRequestDto: {
            name: string;
            fontType: components["schemas"]["FontType"];
            /** Format: binary */
            file: string;
            readonly fileName?: string | null;
        };
        UserFontResponseDto: {
            name?: string | null;
            fontType?: components["schemas"]["FontType"];
            readonly fileName?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
