import type { components } from "./open-api-schema";

export type BootcampRequestDto = Required<components['schemas']['BootcampRequestDto']>;
export type BootcampRequestUpdateDto = Required<components['schemas']['BootcampRequestUpdateDto']>;
export type BootcampResponseDto = Required<components['schemas']['BootcampResponseDto']>;
export type DiplomaSnapshotResponseDto = Required<components['schemas']['DiplomaSnapshotResponseDto']>;
export type FontType = Required<components['schemas']['FontType']>;
export type MakeActiveSnapshotRequestDto = Required<components['schemas']['MakeActiveSnapshotRequestDto']>;
export type PreviewImageRequestDto = Required<components['schemas']['PreviewImageRequestDto']>;
export type StudentRequestDto = Required<components['schemas']['StudentRequestDto']>;
export type StudentResponseDto = Required<components['schemas']['StudentResponseDto']>;
export type StudentUpdateRequestDto = Required<components['schemas']['StudentUpdateRequestDto']>;
export type TemplatePostRequestDto = Required<components['schemas']['TemplatePostRequestDto']>;
export type TemplateRequestDto = Required<components['schemas']['TemplateRequestDto']>;
export type TemplateResponseDto = Required<components['schemas']['TemplateResponseDto']>;
export type TemplateStyle = Required<components['schemas']['TemplateStyle']>;
export type TemplatesResponseDto = Required<components['schemas']['TemplatesResponseDto']>;
export type TracksResponseDto = Required<components['schemas']['TracksResponseDto']>;
export type UserFontRequestDto = Required<components['schemas']['UserFontRequestDto']>;
export type UserFontResponseDto = Required<components['schemas']['UserFontResponseDto']>;