version: '3.9'

services:
  # Frontend
  diploma-maker-test-frontend:
    build:
      context: DiplomaMaker.Web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5258
        VITE_CLERK_PUBLISHABLE_KEY: pk_test_d2lyZWQtYnVjay00Ny5jbGVyay5hY2NvdW50cy5kZXYk
    ports:
      - "5173:80"
    depends_on:
      - diploma-maker-test-backend
    networks:
      - diploma-maker-network

  # Backend
  diploma-maker-test-backend:
    build:
      context: ../Backend/DiplomaMakerApi
      dockerfile: Dockerfile-testing
    ports:
      - "5258:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443
      - ConnectionStrings__PostgreSQLConnectionLocal=Host=diploma-maker-test-postgres-db;Port=5432;Database=diploma_maker_db;Username=postgres;Password=Password_2_Change_4_Real_Cases_&
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google-credentials.json
    secrets:
      - clerk_secretkey
      - clerk_authorizedparty
      - clerk_authority
      - google_credentials
    depends_on:
      diploma-maker-test-postgres-db:
        condition: service_healthy
    volumes:
      - ../Backend/DiplomaMakerApi/Blob:/app/Blob
      - ~/secrets/google-credentials.json:/run/secrets/google-credentials.json
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:443 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - diploma-maker-network

  # PostgreSQL
  diploma-maker-test-postgres-db:
    container_name: diploma-maker-test-postgres-db
    image: postgres:latest
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: 'Password_2_Change_4_Real_Cases_&'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'diploma_maker_db'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - diploma-maker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  diploma-maker-network:
    driver: bridge

volumes:
  postgres-data:

secrets:
  clerk_secretkey:
    file: ~/secrets/clerk-secretKey.txt
  clerk_authorizedparty:
    file: ~/secrets/clerk-authorizedParty.txt
  clerk_authority:
    file: ~/secrets/clerk-authority.txt
  google_credentials:
    file: ~/secrets/google-credentials.json