steps:
## Build Development -----------------------------------------
  # Build container for default deployment
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pgp-sandbox/diplomamakers-frontend:latest', '-f', 'Dockerfile', '.']
    dir: frontend
    id: BuildDefaultFrontend

  # Push the default container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/pgp-sandbox/diplomamakers-frontend:latest']
    id: PushDefaultFrontend
    waitFor: ['BuildDefaultFrontend']

  # Deploy the default container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'frontend-diploma', '--image', 'gcr.io/pgp-sandbox/diplomamakers-frontend:latest', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
    id: DeployDefaultFrontend
    waitFor: ['PushDefaultFrontend']

images:
  - 'gcr.io/pgp-sandbox/diplomamakers-frontend:latest'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
