version:  '3.8'

services:
  backend:
    build:
      context: ./Backend/DiplomaMakerApi
      dockerfile: Dockerfile
    ports:
      - "5268:5268"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend