/*
    BaseEntity

    Defines a base entity from which all model entities inherit.
    Provides them with an Id as autogenerated primary key,
    a guid which can be exposed to the frontend, as well
    as a generic Patch method which updates the value of one entity
    with the non-null values of another entity of the same type.
*/

namespace DiplomaMakerApi._2.Models;

public abstract class BaseEntity<T>()
{
    public virtual int Id { get; init; }
    public Guid Guid { get; init; } = Guid.NewGuid();

    public void Patch(T patch)
    {
        foreach (var property in typeof(T).GetProperties())
        {
            object? patchValue = property.GetValue(patch);
            property.SetValue(this, patchValue is not null
                ? patchValue
                : property.GetValue(this));
        }
    }
}