/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BootcampmanagerImport } from './routes/bootcampmanager'

// Create/Update Routes

const BootcampmanagerRoute = BootcampmanagerImport.update({
  id: '/bootcampmanager',
  path: '/bootcampmanager',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bootcampmanager': {
      id: '/bootcampmanager'
      path: '/bootcampmanager'
      fullPath: '/bootcampmanager'
      preLoaderRoute: typeof BootcampmanagerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/bootcampmanager': typeof BootcampmanagerRoute
}

export interface FileRoutesByTo {
  '/bootcampmanager': typeof BootcampmanagerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/bootcampmanager': typeof BootcampmanagerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/bootcampmanager'
  fileRoutesByTo: FileRoutesByTo
  to: '/bootcampmanager'
  id: '__root__' | '/bootcampmanager'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  BootcampmanagerRoute: typeof BootcampmanagerRoute
}

const rootRouteChildren: RootRouteChildren = {
  BootcampmanagerRoute: BootcampmanagerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/bootcampmanager"
      ]
    },
    "/bootcampmanager": {
      "filePath": "bootcampmanager.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
