// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomaMakerApi.Migrations
{
    [DbContext(typeof(DiplomaMakingContext))]
    [Migration("20240627122253_style")]
    partial class style
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiplomaMakerApi.Models.Bootcamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("graduationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("templateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("templateId");

                    b.ToTable("Bootcamp");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.Diploma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BootcampId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BootcampId");

                    b.ToTable("Diploma");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alignment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FontSize")
                        .HasColumnType("float");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.Property<double?>("XPos")
                        .HasColumnType("float");

                    b.Property<double?>("YPos")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("styles");
                });

            modelBuilder.Entity("Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("basePdf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("footer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("footerStylingId")
                        .HasColumnType("int");

                    b.Property<string>("intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("introStylingId")
                        .HasColumnType("int");

                    b.Property<string>("main")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mainStylingId")
                        .HasColumnType("int");

                    b.Property<string>("templateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("footerStylingId");

                    b.HasIndex("introStylingId");

                    b.HasIndex("mainStylingId");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.Bootcamp", b =>
                {
                    b.HasOne("Template", "template")
                        .WithMany()
                        .HasForeignKey("templateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("template");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.Diploma", b =>
                {
                    b.HasOne("DiplomaMakerApi.Models.Bootcamp", "Bootcamp")
                        .WithMany("Diplomas")
                        .HasForeignKey("BootcampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bootcamp");
                });

            modelBuilder.Entity("Template", b =>
                {
                    b.HasOne("DiplomaMakerApi.Models.Style", "footerStyling")
                        .WithMany()
                        .HasForeignKey("footerStylingId");

                    b.HasOne("DiplomaMakerApi.Models.Style", "introStyling")
                        .WithMany()
                        .HasForeignKey("introStylingId");

                    b.HasOne("DiplomaMakerApi.Models.Style", "mainStyling")
                        .WithMany()
                        .HasForeignKey("mainStylingId");

                    b.Navigation("footerStyling");

                    b.Navigation("introStyling");

                    b.Navigation("mainStyling");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.Bootcamp", b =>
                {
                    b.Navigation("Diplomas");
                });
#pragma warning restore 612, 618
        }
    }
}
