// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomaMakerApi.Migrations
{
    [DbContext(typeof(DiplomaMakingContext))]
    [Migration("20240630121539_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiplomaMakerApi.Models.Bootcamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiplomaTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GraduationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaTemplateId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Bootcamps");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.DiplomaTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BasePdf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Footer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FooterStylingId")
                        .HasColumnType("int");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IntroStylingId")
                        .HasColumnType("int");

                    b.Property<string>("Main")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MainStylingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FooterStylingId");

                    b.HasIndex("IntroStylingId");

                    b.HasIndex("MainStylingId");

                    b.ToTable("DiplomaTemplates");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BootcampId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BootcampId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.TemplateStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alignment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FontSize")
                        .HasColumnType("float");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.Property<double?>("XPos")
                        .HasColumnType("float");

                    b.Property<double?>("YPos")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TemplateStyles");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.Bootcamp", b =>
                {
                    b.HasOne("DiplomaMakerApi.Models.DiplomaTemplate", "DiplomaTemplate")
                        .WithMany()
                        .HasForeignKey("DiplomaTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiplomaTemplate");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.DiplomaTemplate", b =>
                {
                    b.HasOne("DiplomaMakerApi.Models.TemplateStyle", "FooterStyling")
                        .WithMany()
                        .HasForeignKey("FooterStylingId");

                    b.HasOne("DiplomaMakerApi.Models.TemplateStyle", "IntroStyling")
                        .WithMany()
                        .HasForeignKey("IntroStylingId");

                    b.HasOne("DiplomaMakerApi.Models.TemplateStyle", "MainStyling")
                        .WithMany()
                        .HasForeignKey("MainStylingId");

                    b.Navigation("FooterStyling");

                    b.Navigation("IntroStyling");

                    b.Navigation("MainStyling");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.Student", b =>
                {
                    b.HasOne("DiplomaMakerApi.Models.Bootcamp", "Bootcamp")
                        .WithMany("Students")
                        .HasForeignKey("BootcampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bootcamp");
                });

            modelBuilder.Entity("DiplomaMakerApi.Models.Bootcamp", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
