/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FilemanagerImport } from './routes/filemanager'

// Create/Update Routes

const FilemanagerRoute = FilemanagerImport.update({
  id: '/filemanager',
  path: '/filemanager',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/filemanager': {
      id: '/filemanager'
      path: '/filemanager'
      fullPath: '/filemanager'
      preLoaderRoute: typeof FilemanagerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/filemanager': typeof FilemanagerRoute
}

export interface FileRoutesByTo {
  '/filemanager': typeof FilemanagerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/filemanager': typeof FilemanagerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/filemanager'
  fileRoutesByTo: FileRoutesByTo
  to: '/filemanager'
  id: '__root__' | '/filemanager'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  FilemanagerRoute: typeof FilemanagerRoute
}

const rootRouteChildren: RootRouteChildren = {
  FilemanagerRoute: FilemanagerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/filemanager"
      ]
    },
    "/filemanager": {
      "filePath": "filemanager.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
