/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EndpointtestsImport } from './routes/endpointtests'

// Create/Update Routes

const EndpointtestsRoute = EndpointtestsImport.update({
  id: '/endpointtests',
  path: '/endpointtests',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/endpointtests': {
      id: '/endpointtests'
      path: '/endpointtests'
      fullPath: '/endpointtests'
      preLoaderRoute: typeof EndpointtestsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/endpointtests': typeof EndpointtestsRoute
}

export interface FileRoutesByTo {
  '/endpointtests': typeof EndpointtestsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/endpointtests': typeof EndpointtestsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/endpointtests'
  fileRoutesByTo: FileRoutesByTo
  to: '/endpointtests'
  id: '__root__' | '/endpointtests'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  EndpointtestsRoute: typeof EndpointtestsRoute
}

const rootRouteChildren: RootRouteChildren = {
  EndpointtestsRoute: EndpointtestsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/endpointtests"
      ]
    },
    "/endpointtests": {
      "filePath": "endpointtests.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
