version: '3.9'

services:

  # Frontend
  diploma-maker-test-frontend:
    build:
      context: ../DiplomaMaker.Web
      dockerfile: Dockerfile
    ports:
      - "3100:80"
    depends_on:
      - diploma-maker-test-backend
    networks:
      - diploma-maker-network

  # Backend
  diploma-maker-test-backend:
    build:
      context: ../../Backend/DiplomaMakerApi
      dockerfile: Dockerfile
    ports:
      - "5100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ConnectionStrings__Postgres=Host=diploma-maker-test-postgres-db;Port=5434;Database=diploma_maker_db;Username=postgres;Password=Password_2_Change_4_Real_Cases_&
    depends_on:
      - diploma-maker-test-postgres-db
    networks:
      - diploma-maker-network

  # PostgreSQL
  diploma-maker-test-postgres-db:
    container_name: diploma-maker-test-postgres-db
    image: postgres:latest
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: 'Password_2_Change_4_Real_Cases_&'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'diploma_maker_db'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - diploma-maker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  diploma-maker-network:
    driver: bridge

volumes:
  postgres-data: