name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: diploma_maker_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password_2_Change_4_Real_Cases_&
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore $GITHUB_WORKSPACE/Backend/DiplomaMakerApi/DiplomaMakerApi.csproj

    - name: Build
      run: dotnet build --no-restore $GITHUB_WORKSPACE/Backend/DiplomaMakerApi

    - name: Set file permissions
      run: chmod -R 777 $GITHUB_WORKSPACE

    - name: Setup Google Credentials
      run: echo "$GOOGLE_CREDENTIALS" > $HOME/gcloud.json
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set Google Application Credentials
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json" >> $GITHUB_ENV

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for PostgreSQL..."
        until pg_isready -h localhost -p 5432; do sleep 1; done

    - name: Test
      run: dotnet test --logger "console;verbosity=detailed" $GITHUB_WORKSPACE/Backend/DiplomaMakerApi.Tests.Integration/DiplomaMakerApi.Tests.Integration.csproj
