# This workflow will build a .NET project and run integration tests with Docker support

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: diploma_maker_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password_2_Change_4_Real_Cases_&
        ports:
          - 5432:5432
        options: > 
          --health-cmd "pg_isready" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        sudo systemctl start docker
        sudo docker --version

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore $GITHUB_WORKSPACE/Backend/DiplomaMakerApi/DiplomaMakerApi.csproj

    - name: Build
      run: dotnet build --no-restore $GITHUB_WORKSPACE/Backend/DiplomaMakerApi

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for PostgreSQL..."
        until pg_isready -h localhost -p 5432; do sleep 1; done

    - name: Test
      run: dotnet test $GITHUB_WORKSPACE/Backend/DiplomaMakerApi.Tests.Integration/DiplomaMakerApi.Tests.Integration.csproj
